### ISSUE TITLE
No supported files found"

### ISSUE THREAD

**Issue by hulongping** [zxdawn/FY-4#3]
>>>filenames = glob.glob('fy4a-_agri--_n_disk_1047e_l1-_fdi-_mult_nom_20190810000000_20190810001459_4000m_v0001.hdf')
>>> scn = Scene(filenames, reader='agri_l1')

raise ValueError("No supported files found")

print(satpy.available_readers())
['abi_l1b', 'abi_l1b_scmi', 'abi_l2_nc', 'acspo', 'agri_l1', 'ahi_hrit', 'ahi_hsd', 'ahi_l1b_gridded_bin', 'ami_l1b', 'amsr2_l1b', 'amsr2_l2', 'amsr2_l2_gaasp', 'avhrr_l1b_aapp', 'avhrr_l1b_eps', 'avhrr_l1c_eum_gac_fdr_nc', 'cmsaf-claas2_l2_nc', 'electrol_hrit', 'fci_l1c_fdhsi', 'fci_l2_nc', 'generic_image', 'geocat', 'glm_l2', 'goes-imager_hrit', 'goes-imager_nc', 'gpm_imerg', 'hy2_scat_l2b_h5', 'iasi_l2', 'jami_hrit', 'maia', 'mersi2_l1b', 'mimicTPW2_comp', 'mtsat2-imager_hrit', 'mviri_l1b_fiduceo_nc', 'nucaps', 'nwcsaf-geo', 'nwcsaf-msg2013-hdf5', 'nwcsaf-pps_nc', 'olci_l1b', 'olci_l2', 'omps_edr', 'safe_sar_l2_ocn', 'sar-c_safe', 'satpy_cf_nc', 'seviri_l1b_hrit', 'seviri_l1b_native', 'seviri_l1b_nc', 'slstr_l1b', 'slstr_l2', 'smos_l2_wind', 'tropomi_l2', 'vaisala_gld360', 'vii_l1b_nc', 'vii_l2_nc', 'viirs_compact', 'viirs_edr_active_fires', 'viirs_l1b', 'viirs_sdr', 'virr_l1b']

**Comment by zxdawn** [comment]
The original filename should be like this:

```
FY4A-_AGRI--_N_REGC_1047E_L1-_FDI-_MULT_NOM_20190831221500_20190831221916_4000M_V0001.HDF
```

I guess that's the problem of uppercase.
