### ISSUE TITLE
关于无法绘制其他合成方案

### ISSUE THREAD

**Issue by MengXin001** [zxdawn/FY-4#4]
使用4KM全圆盘数据尝试输出过可用合成方案`scn.available_composite_names()`
返回结果
`Too many possible datasets to load for DataQuery(wavelength=3.9)`
`Too many possible datasets to load for DataQuery(wavelength=3.9)`
`Too many possible datasets to load for DataQuery(wavelength=3.9)`
`Too many possible datasets to load for DataQuery(wavelength=3.9)`
`Too many possible datasets to load for DataQuery(wavelength=3.9)`
以上不影响绘制。真彩色；自然光；沙尘；雾等产品均可出图
剩余```'night_background''night_background_hires```等合成报错
**`raise MissingDependencies(unknown_datasets, "Unknown datasets:")
satpy.node.MissingDependencies: Unknown datasets: {DataQuery(name='night_background')}`**

**Comment by zxdawn** [comment]
报错的两个是因为没有加到agri的composites里面。具体添加方法见[手册](https://satpy.readthedocs.io/en/stable/composites.html)
