### ISSUE TITLE
关于FY4A问题求助

### ISSUE THREAD

**Issue by ZouR-Ma** [zxdawn/FY-4#5]
学长你好，我现在已经将FY4的文件提取成图片，由于FY4是标称投影（这个投影好像没有国际标准），请问你有试过将标称投影图片转墨卡托投影的经验嘛

**Comment by zxdawn** [comment]
你好，你问的应该是画图使用mercator投影吧，可以参考[cartopy的教程](https://scitools.org.uk/cartopy/docs/latest/tutorials/understanding_transform.html)。
