### ISSUE TITLE
关于数据格式的求助

### ISSUE THREAD

**Issue by kaka0910** [zxdawn/FY-4#6]
您好，请问一下为什么我读单个文件会报错呢？期待您的解答
我加载风云四的命令：
filenames =glob.glob("FY4A-_AGRI--_N_DISK_1047E_L1-_FDI-_MULT_NOM_20200901000000_20200901001459_4000M_V0001.HDF")

报错信息：
Don't know how to open the following files: {'/Users/kaka/Desktop/AI_MR/FY4A-_AGRI--_N_DISK_1047E_L1-_FDI-_MULT_NOM_20200901000000_20200901001459_4000M_V0001.HDF'}
ValueError: No supported files found

**Comment by zxdawn** [comment]
你好，请问你是用的satpy最新版本吗？

**Comment by kaka0910** [comment]
您好，satpy版本是0.33.0，python版本是3.7.0

**Comment by zxdawn** [comment]
那应该没问题。你把这个的输出结果贴上来看看呢：
```
import satpy

print(satpy.available_readers())
```

**Comment by kaka0910** [comment]
print的结果是这个：
>>> print(satpy.available_readers())
['abi_l1b', 'abi_l1b_scmi', 'abi_l2_nc', 'ahi_hrit', 'ahi_hsd', 'ahi_l1b_gridded_bin', 'amsr2_l2_gaasp', 'amsub_l1c_aapp', 'avhrr_l1b_aapp', 'avhrr_l1b_eps', 'avhrr_l1c_eum_gac_fdr_nc', 'electrol_hrit', 'fci_l2_nc', 'glm_l2', 'goes-imager_hrit', 'goes-imager_nc', 'jami_hrit', 'mhs_l1c_aapp', 'mirs', 'mtsat2-imager_hrit', 'mviri_l1b_fiduceo_nc', 'nwcsaf-geo', 'nwcsaf-pps_nc', 'olci_l1b', 'olci_l2', 'safe_sar_l2_ocn', 'satpy_cf_nc', 'seviri_l1b_hrit', 'seviri_l1b_native', 'seviri_l1b_nc', 'slstr_l1b', 'slstr_l2', 'vaisala_gld360']

是因为没有agri_l1吗？
但是我satpy/readers/文件夹下是有agri_l1.py这个文件的～

**Comment by zxdawn** [comment]
你可以检查一下，你的运行环境是否一致。

**Comment by kaka0910** [comment]
运行环境是一致的😭

**Comment by zxdawn** [comment]
那你检查一下
```
import satpy
print(satpy.__file__)
```

**Comment by kaka0910** [comment]
您好，输出的是这个：
/Users/kaka/opt/anaconda3/envs/sat37/lib/python3.7/site-packages/satpy/__init__.py

**Comment by zxdawn** [comment]
那你看看/Users/kaka/opt/anaconda3/envs/sat37/lib/python3.7/site-packages/satpy/readers下面有没有agri_l1.py

**Comment by kaka0910** [comment]
有的
但是之前satpy.available_readers()这个找不着agri_l1

**Comment by zxdawn** [comment]
那就奇怪了.....可以新建个环境测试一下,感觉不太正常

**Comment by kaka0910** [comment]
吼哒，谢谢！我再试一下~

**Comment by kaka0910** [comment]
您好，我重新装了一下环境，就可以了！！！
我想了想应该是上次我装命令的时候，没有写conda-forge
感谢帮助！！！

**Comment by zxdawn** [comment]
不客气,推荐如果使用的科学计算包多的话,可以把.condarc改一下,让他所有的包默认都从conda-forge装.
